/**
 * Unified area sub-page data for all emirates (Phase 1 local long-tail).
 * Each emirate has a city page (/sofa-cleaning-{emirate}) plus per-area pages
 * (/sofa-cleaning-{emirate}/[slug]) with unique copy to avoid thin duplicates.
 */
import type { Metadata } from 'next';

export interface Area {
  slug: string;
  name: string;   // full display name
  short: string;  // short label
  propertyType: string;
  intro: string;
  whyClean?: string;
  serviceDetail?: string;
  landmarks: string[];
  localNote: string;
  faqs: { q: string; a: string }[];
}

export interface EmirateConfig {
  key: string;
  cityName: string;   // "Dubai"
  citySlug: string;   // "sofa-cleaning-dubai"
  areas: Area[];
}

const BASE = 'https://sofashampooingdubai.com';

export const emirates: Record<string, EmirateConfig> = {
  dubai: {
    key: 'dubai', cityName: 'Dubai', citySlug: 'sofa-cleaning-dubai',
    areas: [
      { slug: 'dubai-marina', name: 'Dubai Marina', short: 'Marina', propertyType: 'high-rise waterfront apartments',
        intro: 'Dubai Marina living means high-rise apartments where sea humidity and fine dust settle deep into sofa fabric within weeks of moving in. Towers along the waterfront — from Marina Diamonds and Princess Tower to JBR and Marina Walk — pack thousands of households into a compact strip, and busy shared lobbies bring in extra dust and pollen. Al Haya Sofa Care brings professional deep shampoo & steam cleaning right to your apartment door, with flexible evening and weekend slots for residents working long hours in nearby DIFC and Media City. No need to move furniture out; our team works on-site with quick-dry extraction so your living room is usable again the same afternoon.',
        whyClean: 'Marina apartments sit just meters from the sea, and the constant onshore breeze carries fine salt particles and humidity that soak into fabric fibers and foam padding over time. High-rise ventilation and central AC systems also recirculate dust from balconies and shared corridors, so sofas here collect grime faster than inland homes. Add in Marina\'s dense population of young professionals and tenants who entertain often, and spills, wine stains and everyday wear pile up quickly. Regular professional cleaning stops moisture and salt residue from breaking down fabric and foam long-term.',
        serviceDetail: 'For Marina\'s mostly compact 1- to 3-bedroom apartments, our technicians use a low-moisture shampoo and hot-water steam extraction method that lifts embedded salt and dust without oversaturating fabric — important given the building\'s already-high humidity. We bring portable, self-contained equipment up in the elevator, so there\'s no water connection or mess in your unit. Fabric sofas are typically dry within 3–4 hours thanks to high-velocity air movers; leather sectionals get a gentler wipe-clean and conditioning pass. We work around concierge access rules and move-in/move-out schedules common across Marina towers.',
        landmarks: ['Marina Walk', 'Princess Tower', 'Marina Diamonds', 'Ocean Heights', 'JBR', 'Marina Promenade', 'Cayan Tower', 'Dubai Marina Mall', 'Bluewaters Island'],
        localNote: 'Marina’s waterfront humidity speeds up fabric deterioration and odors — we recommend a professional sofa clean every 4–6 months for Marina apartments. Many residents book alongside an annual deep-cleaning schedule or before hosting guests during the cooler season, when Marina Walk and JBR bring more visitors through the home.',
        faqs: [
          { q: 'Do you provide sofa cleaning inside Dubai Marina towers?', a: 'Yes. Our mobile team brings all equipment to your apartment in any Marina tower — Princess Tower, Marina Diamonds, Ocean Heights and more. Same-day slots are usually available.' },
          { q: 'How long does a Marina apartment sofa clean take?', a: 'A standard 3-seater takes about 1–2 hours and is dry within 3–4 hours, so it fits easily into a busy Marina schedule.' },
          { q: 'How much does sofa cleaning cost in Dubai Marina?', a: 'Pricing starts from AED 79 for shampooing, AED 89 for steam cleaning, AED 99 for deep cleaning, and AED 129 for leather sofas. WhatsApp +971547199189 for a free quote based on your sofa size.' },
          { q: 'Can I book same-day sofa cleaning in Marina?', a: 'Usually, yes. Message us in the morning and our team can often fit you in the same afternoon or evening across Marina towers.' },
          { q: 'Are your cleaning products safe for kids and pets in Marina apartments?', a: 'Yes — every product we use is eco-friendly and non-toxic, which matters in Marina\'s compact apartments where sofas double as play and lounging space.' },
        ] },
      { slug: 'jvc', name: 'JVC (Jumeirah Village Circle)', short: 'JVC', propertyType: 'family apartments, townhouses and villas',
        intro: 'JVC is one of Dubai\'s fastest-growing family communities — a mix of low-rise apartments, townhouses and villas where everyday use, kids and pets take a real toll on sofas. New buildings keep opening across JVC\'s circular district layout, and many households moved in with fresh furniture that still needs regular upkeep to stay looking new. Al Haya Sofa Care offers same-day at-home sofa deep shampoo, steam cleaning and stain removal across all JVC districts, with pricing that suits the community\'s young family budgets. Our team is familiar with JVC\'s building access procedures and villa compounds alike.',
        whyClean: 'JVC\'s popularity with young families means sofas see heavy daily use — juice spills, crayon marks, muddy paws after a walk around Circle Mall, and general wear from active kids. Construction dust is still common in parts of JVC as new towers and villas continue to rise nearby, settling into fabric through open windows and balconies. Many homes also run central AC year-round, which circulates dust throughout the living room. Regular deep cleaning keeps sofas hygienic for children playing on them and extends the life of newer furniture.',
        serviceDetail: 'Because JVC mixes apartments, townhouses and standalone villas, our technicians adapt the approach on-site: compact apartment sofas get quick low-moisture steam cleaning, while larger townhouse and villa sectionals get full hot-water extraction for deeper stain and allergen removal. We carry enzyme-based treatments specifically for pet and child-related stains, which are common across JVC households. Fabric sofas dry within 3–4 hours with our air movers, so families aren\'t without their living room for long. We can also schedule around school pick-up times for a smoother visit.',
        landmarks: ['Circle Mall', 'JVC District 10–16', 'Seasons Community', 'Plazzo Residence', 'JSS International School', 'Diamond Views', 'FIVE JVC'],
        localNote: 'Family homes in JVC with children or pets benefit from a deep clean every 3–4 months to control allergens and stains. Many residents pair sofa cleaning with a broader home refresh when moving into a new JVC tower or townhouse.',
        faqs: [
          { q: 'Do you cover all JVC districts for sofa cleaning?', a: 'Yes — we serve every JVC district (10 through 16 and beyond), covering apartments, townhouses and villas with the same at-home service.' },
          { q: 'Can you remove pet stains from sofas in JVC?', a: 'Absolutely. We use enzyme-based pet stain and odor treatments safe for fabric and leather, ideal for JVC\'s many pet-owning families.' },
          { q: 'What does sofa cleaning cost in JVC?', a: 'From AED 79 for shampooing and AED 99 for deep cleaning, with townhouse and villa sectionals priced by size. WhatsApp +971547199189 for an exact quote.' },
          { q: 'How do I book a sofa cleaning appointment in JVC?', a: 'Simply message us on WhatsApp with your building or community name and preferred time — most JVC bookings can be confirmed the same day.' },
          { q: 'Do you clean fabric sofas as well as leather in JVC homes?', a: 'Yes — we handle all fabric types including microfiber, cotton blends and linen, plus leather sofas from AED 129 with specialist conditioning.' },
        ] },
      { slug: 'business-bay', name: 'Business Bay', short: 'Business Bay', propertyType: 'high-rise apartments and offices',
        intro: 'Business Bay\'s mix of residential towers, hotel apartments and offices along the Dubai Canal means sofas and reception seating face heavy daily use from residents and visiting clients alike. The district\'s canal-side towers combine live-work lifestyles, so many apartments double as home offices where the sofa gets used all day rather than just in the evening. Al Haya Sofa Care provides professional sofa shampooing, steam sanitization and upholstery cleaning for both homes and offices across Business Bay, with flexible timing that avoids disrupting your workday or business hours.',
        whyClean: 'Business Bay\'s density of towers around the canal creates constant construction and traffic dust that settles on upholstery through balconies and building ventilation. Office reception areas and meeting-room seating see a steady stream of visitors, tracking in dirt and oils that build up on fabric and leather far faster than in a typical home. Canal-facing apartments also deal with reflected humidity off the water. Regular professional cleaning keeps both residential sofas and commercial seating presentable and hygienic for clients and family.',
        serviceDetail: 'For Business Bay\'s offices, we schedule after-hours or weekend visits so reception sofas, waiting-area seating and meeting-room chairs are cleaned without interrupting business operations, and we can sanitize with high-temperature steam that kills bacteria before the next workday. In residential towers, we bring the same steam extraction and shampoo process used in homes citywide, sized to fit Business Bay\'s mix of studio, one-bedroom and larger canal-view units. Building access and loading-dock coordination for taller towers like The Opus and Executive Towers is handled by our team in advance.',
        landmarks: ['Bay Square', 'Executive Towers', 'The Opus', 'Business Bay Metro', 'Canal-side towers', 'Dubai Canal Promenade', 'Bay Avenue'],
        localNote: 'For Business Bay offices, after-hours and weekend slots keep your workspace seating fresh without downtime. Residential towers along the canal often book quarterly cleaning to manage humidity-related odors before they set in.',
        faqs: [
          { q: 'Do you clean office sofas and reception seating in Business Bay?', a: 'Yes. We handle office reception sofas, waiting-area seating and meeting-room chairs in Business Bay, with flexible after-hours scheduling.' },
          { q: 'Is steam sanitization available in Business Bay?', a: 'Yes — high-temperature steam cleaning that kills 99.9% of bacteria is available for all Business Bay homes and offices.' },
          { q: 'How much does sofa or office seating cleaning cost in Business Bay?', a: 'Home sofa cleaning starts from AED 79; office seating is quoted by number of pieces. WhatsApp +971547199189 with your requirements for a fast quote.' },
          { q: 'Can you book around our office hours in Business Bay?', a: 'Yes — we regularly schedule evening, weekend or early-morning visits so office cleaning never interferes with client meetings or staff.' },
          { q: 'How long before an office sofa is dry and usable again?', a: 'Most fabric seating is dry within 3–4 hours using our air movers, and leather reception sofas can be used again almost immediately after conditioning.' },
        ] },
      { slug: 'jumeirah', name: 'Jumeirah', short: 'Jumeirah', propertyType: 'luxury villas and beachfront homes',
        intro: 'Jumeirah\'s luxury villas and beachfront homes, stretching from Jumeirah Beach Road down to La Mer, often feature premium fabrics and full-grain leather that need specialist care rather than a generic cleaning approach. Large formal living rooms and outdoor-facing majlis seating are common in this established, low-density community, and homeowners expect a discreet, careful service that matches the quality of their furniture. Al Haya Sofa Care delivers gentle, pH-balanced deep cleaning and leather conditioning that protects high-end upholstery against coastal humidity and sun exposure, without harsh chemicals that could damage designer fabrics.',
        whyClean: 'Jumeirah\'s beachfront position exposes villas to constant salt-laden sea breeze, which settles into fabric weave and leather grain and, left untreated, leads to cracking, fading and musty odors over time. Large windows and open-plan living areas common in Jumeirah villas also mean more direct sunlight on upholstery, which dries out leather and bleaches fabric color unevenly. Many homes here entertain guests regularly in formal sitting rooms, adding wear on top of the environmental factors. Professional, fabric-appropriate cleaning protects the investment in premium sofas and keeps them looking new for years.',
        serviceDetail: 'In Jumeirah villas, our technicians start with a fabric or leather assessment to choose the safest method — low-moisture dry foam for velvet and silk blends, pH-balanced shampoo for cotton and linen weaves, and specialist conditioning creams for leather that restore suppleness without altering the finish. Large L-shaped and sectional sofas typical of Jumeirah\'s formal living rooms are cleaned in sections to control drying time, usually 4–6 hours for fabric. We work discreetly and can coordinate around household staff or scheduled family time, treating each villa visit as a private, unhurried appointment.',
        landmarks: ['Jumeirah Beach Road', 'Mercato Mall', 'La Mer', 'Jumeirah 1–3', 'Jumeirah Mosque', 'Kite Beach', 'Jumeirah Fishing Harbour'],
        localNote: 'Beachfront homes in Jumeirah face salt-air humidity — regular professional care protects premium leather and fabric from cracking and musty odors. Many villa owners schedule cleaning ahead of family gatherings or seasonal changes when sun exposure is highest.',
        faqs: [
          { q: 'Do you clean luxury leather sofas in Jumeirah?', a: 'Yes. We use specialist pH-safe leather cleaning and conditioning to protect premium leather sofas in Jumeirah villas from cracking and dryness.' },
          { q: 'Can you handle delicate fabrics like velvet and silk?', a: 'Yes — we use low-moisture techniques for velvet, silk and other delicate upholstery common in Jumeirah\'s luxury homes.' },
          { q: 'What does sofa cleaning cost for a large Jumeirah villa sofa?', a: 'Leather sofas start from AED 129 and large fabric sectionals are quoted by size. WhatsApp +971547199189 with a photo for an accurate quote.' },
          { q: 'How do I schedule a private appointment for my Jumeirah villa?', a: 'Message us on WhatsApp with your preferred date and time — we accommodate discreet, household-staff-coordinated visits across Jumeirah 1, 2 and 3.' },
          { q: 'How long does a formal living room sofa take to dry?', a: 'Large sectional and L-shaped sofas typical of Jumeirah villas are usually dry within 4–6 hours with our professional air-movement drying process.' },
        ] },
      { slug: 'al-barsha', name: 'Al Barsha', short: 'Al Barsha', propertyType: 'villas and family apartments',
        intro: 'Al Barsha is a well-established residential hub of villas and family apartments spread across Al Barsha 1 through 3 and Al Barsha South, all within easy reach of Mall of the Emirates. It\'s one of Dubai\'s more diverse, long-settled neighborhoods, with a mix of older independent villas and newer apartment buildings housing large multi-generational families. Al Haya Sofa Care provides affordable, same-day sofa deep cleaning, shampooing and stain removal across all Al Barsha communities, sized right for busy family homes that don\'t have time to wait days for a booking.',
        whyClean: 'Al Barsha\'s older villa stock and busy family households mean sofas often see years of accumulated dust, food spills and pet activity before their first professional clean. The area\'s proximity to Sheikh Zayed Road and Al Barsha\'s own busy internal roads brings in traffic dust through windows and building vents. With many households running larger families and frequent guests for gatherings, sofas absorb odors and stains faster than smaller households elsewhere in Dubai. A scheduled deep clean keeps allergens down and extends the usable life of well-loved family furniture.',
        serviceDetail: 'Given Al Barsha\'s mix of villas and apartments, our team brings full hot-water extraction equipment for larger villa sofas and lighter, quicker steam methods for apartment-sized pieces. We prioritize stain-specific pre-treatment for common household marks — food, juice, ink and pet accidents — before the main shampoo pass, which is especially useful for busy family homes. Most jobs are completed within 1–2 hours and sofas are dry within 3–4 hours. We also offer flexible same-day booking so families don\'t need to plan days in advance.',
        landmarks: ['Mall of the Emirates', 'Al Barsha 1–3', 'Al Barsha South', 'Dubai Hills border', 'Al Barsha Pond Park', 'American School of Dubai'],
        localNote: 'High-traffic family villas in Al Barsha benefit from a deep clean every 4–6 months to keep sofas hygienic and fresh. Larger households with regular guests often move to a quarterly schedule to stay ahead of stains and odors.',
        faqs: [
          { q: 'Is same-day sofa cleaning available in Al Barsha?', a: 'Yes — we offer same-day at-home sofa cleaning across Al Barsha 1, 2, 3 and Al Barsha South. WhatsApp us to book a slot.' },
          { q: 'How much does sofa cleaning cost in Al Barsha?', a: 'Pricing starts from AED 79 for shampooing and AED 99 for deep cleaning, with at-home doorstep service included.' },
          { q: 'Can you clean large family villa sofas in Al Barsha?', a: 'Yes — we regularly service large L-shaped and multi-seater sofas in Al Barsha villas, with pricing based on sofa size.' },
          { q: 'Do you offer eco-friendly cleaning safe for a large family in Al Barsha?', a: 'Yes, all products are eco-friendly and non-toxic, safe for children, elderly family members and pets common in Al Barsha households.' },
          { q: 'How do I book sofa cleaning in Al Barsha?', a: 'Just WhatsApp +971547199189 with your community (Al Barsha 1, 2, 3 or South) and preferred time — most requests are confirmed within minutes.' },
        ] },
      { slug: 'jlt', name: 'JLT (Jumeirah Lakes Towers)', short: 'JLT', propertyType: 'lakeside residential and office towers',
        intro: 'JLT\'s 26 clusters of lakeside towers mix residential apartments with DMCC-registered offices, creating one of Dubai\'s densest live-work communities around a chain of artificial lakes. The lake-side humidity, combined with heavy foot traffic through shared podium retail and metro access, can trap moisture and dust in upholstery faster than drier inland districts. Al Haya Sofa Care serves all JLT clusters — A through Z — with professional sofa shampooing, steam cleaning and odor treatment for both apartments and office seating, scheduled to fit around JLT\'s always-busy building lobbies and lift access.',
        whyClean: 'JLT\'s cluster of towers sits directly around man-made lakes, and the resulting ambient humidity settles into fabric fibers and can trap odor-causing moisture deep in sofa cushions if left unaddressed. Many JLT apartments are also rented short-term or used as serviced offices, meaning higher turnover and less consistent furniture care between tenants. Office seating in DMCC-registered companies sees daily client and staff use across long working hours. Together, these factors make JLT sofas more prone to musty smells and visible wear than a typical low-density residential area.',
        serviceDetail: 'Our JLT visits combine hot-water steam extraction with a targeted deodorizing treatment that neutralizes lake-humidity odors at the source rather than masking them with fragrance. For office clusters, we coordinate with building management for loading access and can work after hours to avoid disrupting DMCC business operations. Apartment sofas typically take 1–2 hours to clean and 3–4 hours to dry with our air movers; we always confirm your specific cluster and tower on booking since JLT\'s A–Z layout can be confusing for first-time visitors.',
        landmarks: ['JLT Cluster A–Z', 'Almas Tower', 'Lake View Towers', 'DMCC', 'JLT Park', 'JLT Metro Station', 'Indigo Icon Tower'],
        localNote: 'Lakeside humidity in JLT can cause musty sofa odors — professional steam cleaning every 4–6 months keeps upholstery fresh. Office clusters often prefer quarterly cleaning to maintain a professional appearance for visiting clients.',
        faqs: [
          { q: 'Which JLT clusters do you cover for sofa cleaning?', a: 'All of them — clusters A through Z. We regularly service residential and office towers across JLT with at-home and on-site cleaning.' },
          { q: 'Can you treat musty sofa odors caused by JLT humidity?', a: 'Yes. Our steam cleaning and deodorizing treatment neutralizes humidity-related odors at the source rather than masking them.' },
          { q: 'What is the cost of sofa cleaning in JLT?', a: 'From AED 79 for shampooing, AED 89 for steam cleaning and AED 99 for deep cleaning. WhatsApp +971547199189 with your cluster for a quote.' },
          { q: 'Can you clean office seating in DMCC towers within JLT?', a: 'Yes — we service office reception and meeting-room seating across JLT\'s DMCC-registered towers, with after-hours scheduling available.' },
          { q: 'How quickly can I get a sofa cleaning appointment in JLT?', a: 'Same-day or next-day slots are usually available — just confirm your cluster letter and tower name when you message us.' },
        ] },
      { slug: 'downtown-dubai', name: 'Downtown Dubai', short: 'Downtown', propertyType: 'premium apartments and penthouses',
        intro: 'Downtown Dubai\'s premium apartments and penthouses — clustered around Burj Khalifa, Dubai Mall and the Opera District — deserve meticulous upholstery care that matches the standard of the address. Residents here often furnish with designer fabrics, Italian leather and statement sectionals sourced from high-end showrooms, and expect a service that treats each piece individually rather than a one-size-fits-all wash. Al Haya Sofa Care provides discreet, professional sofa deep cleaning and leather care for high-end Downtown residences, using eco-friendly products that are safe for luxury finishes and won\'t void manufacturer warranties.',
        whyClean: 'Downtown\'s ultra-dense cluster of towers around Burj Khalifa means constant foot traffic through lobbies, valet areas and building amenities, tracking fine dust and pollutants up into apartments via lift systems and central AC. Many Downtown residences are also short-let or investor-owned units with rotating occupants, so sofas often go unmaintained between tenancies until visible soiling sets in. The premium fabrics and leathers common here are more sensitive to incorrect cleaning products than everyday upholstery, so improper DIY attempts can cause lasting damage. Professional, fabric-matched cleaning protects both appearance and resale value.',
        serviceDetail: 'We begin every Downtown appointment with a fabric and finish assessment — full-grain leather, suede, velvet and tightly woven designer fabrics all require different products and pressure settings. Our technicians use pH-balanced, low-residue shampoo for fabric pieces and specialist conditioning creams for leather that restore shine without altering the original finish. We coordinate building access with concierge teams common in Address Residences and Opera District towers, and can schedule discreet appointments that avoid disrupting a household\'s day. Fabric sofas are typically dry within 3–4 hours.',
        landmarks: ['Burj Khalifa', 'Dubai Mall', 'The Address Residences', 'Opera District', 'Boulevard', 'Dubai Fountain', 'Burj Park'],
        localNote: 'High-end Downtown interiors warrant gentle, premium cleaning — we tailor every treatment to the fabric and finish. Investor-owned units between tenancies often benefit from a full refresh before new occupants move in.',
        faqs: [
          { q: 'Do you offer premium sofa cleaning in Downtown Dubai?', a: 'Yes. We provide careful, premium sofa deep cleaning and leather conditioning for Downtown apartments, penthouses and Address Residences.' },
          { q: 'Are your products safe for luxury upholstery?', a: 'Yes — all products are eco-friendly, non-toxic and pH-balanced, chosen specifically for the fabric or leather of each high-end piece.' },
          { q: 'What is the cost of leather sofa cleaning in Downtown Dubai?', a: 'Leather conditioning starts from AED 129, with fabric sofas from AED 79. WhatsApp +971547199189 with photos for an exact quote on designer pieces.' },
          { q: 'Can you clean a sofa before new tenants move into a Downtown unit?', a: 'Yes — this is a common request from investor-owned units in Downtown, and we can schedule around move-in/move-out timelines.' },
          { q: 'Do you handle building concierge and access coordination in Downtown towers?', a: 'Yes — we regularly coordinate with concierge and building management in towers around Address Residences and the Opera District ahead of the visit.' },
        ] },
      { slug: 'palm-jumeirah', name: 'Palm Jumeirah', short: 'Palm Jumeirah', propertyType: 'beachfront villas and luxury apartments',
        intro: 'Palm Jumeirah\'s beachfront villas and luxury apartments — spread across the trunk, fronds and Golden Mile — face constant salt-air humidity that\'s tough on premium sofas, whether it\'s a frond villa\'s formal majlis or a Shoreline Apartments living room facing the open sea. Homes here are typically furnished at a high standard, with imported fabrics and leather that need careful, fabric-matched handling rather than generic cleaning chemicals. Al Haya Sofa Care offers specialist deep cleaning, fast-dry extraction and leather conditioning that protects high-value upholstery in Palm residences, with a service level that matches the address.',
        whyClean: 'Palm Jumeirah sits fully exposed to the open Gulf, and its constant sea breeze carries higher salt concentration than mainland coastal areas like Jumeirah or JBR, accelerating fabric breakdown and leather cracking if sofas aren\'t cleaned regularly. Frond villas often have large glass doors opening directly onto private beaches, letting in sand and salt air throughout the day. Many Palm residences are also holiday homes or investment properties used seasonally, so sofas can go months without use and still need refreshing before guests arrive. Fast, thorough cleaning is essential to protect the investment in premium furniture here.',
        serviceDetail: 'For Palm villas and apartments, we use fast-dry hot-water extraction specifically chosen to remove trapped salt-air moisture before it settles permanently into foam and fabric backing, cutting typical dry time to around 3–4 hours despite the humid coastal setting. Leather sofas receive a full conditioning treatment that restores oils lost to sun and salt exposure. We also offer an optional protective fabric coat after cleaning that helps repel humidity and everyday spills between visits — popular with frond villa owners who host frequently. Access coordination for gated fronds and villa security is arranged ahead of each visit.',
        landmarks: ['Palm Jumeirah Crescent', 'Atlantis', 'Golden Mile', 'Shoreline Apartments', 'Palm Trunk', 'Nakheel Mall', 'The Pointe', 'Palm West Beach'],
        localNote: 'Salt-air humidity on the Palm accelerates fabric and leather wear — fast-dry professional cleaning every 4–6 months is ideal. Seasonal or holiday-home owners often book ahead of guest arrivals to refresh sofas that have sat unused.',
        faqs: [
          { q: 'Do you serve villas and apartments on Palm Jumeirah?', a: 'Yes — we cover Shoreline Apartments, Golden Mile, and beachfront villas across the Palm Jumeirah trunk and fronds.' },
          { q: 'How do you protect sofas from Palm Jumeirah humidity?', a: 'We use fast-dry extraction to remove trapped moisture and offer a protective fabric coat to repel humidity and stains between cleans.' },
          { q: 'What does sofa cleaning cost for a Palm Jumeirah villa?', a: 'Leather from AED 129, fabric sofas from AED 79, with large frond villa sectionals quoted by size. WhatsApp +971547199189 for a quote.' },
          { q: 'Can you clean a holiday home sofa before guests arrive on the Palm?', a: 'Yes — this is a common request. We can schedule a fast-dry clean timed to finish before check-in so the sofa is ready to use.' },
          { q: 'Do you handle gated villa and frond security access on Palm Jumeirah?', a: 'Yes — we coordinate access passes and security clearance for gated fronds in advance so the visit runs smoothly on arrival.' },
        ] },
    ],
  },
  sharjah: {
    key: 'sharjah', cityName: 'Sharjah', citySlug: 'sofa-cleaning-sharjah',
    areas: [
      { slug: 'al-nahda', name: 'Al Nahda Sharjah', short: 'Al Nahda', propertyType: 'dense residential apartments',
        intro: 'Al Nahda is one of Sharjah’s busiest residential areas, packed with family apartment buildings right on the Dubai border. Its narrow streets and close-set towers mean traffic dust and construction grit are constant companions for local households. Al Haya Sofa Care offers convenient at-home sofa shampoo and steam cleaning across Al Nahda — quick-dry, eco-friendly and same-day. Many residents commute daily into Dubai, so our flexible evening and weekend slots fit busy schedules without disrupting the household.',
        whyClean: 'Al Nahda’s dense apartment blocks trap airborne dust from nearby roads and ongoing construction, and that fine grit works its way deep into sofa fibers within weeks. Combined with high foot traffic in smaller family units, fabric sofas here darken and flatten faster than in quieter suburbs. Regular professional shampooing lifts embedded grit before it abrades the weave, while steam sanitization tackles allergens that build up in shared, tightly packed living spaces. Skipping cleaning for too long lets dust settle permanently into the fabric base, making stains far harder to lift later.',
        serviceDetail: 'Our Al Nahda team uses hot-water extraction shampooing (AED 79) to flush dust and grime from deep within the cushion foam and fabric backing, followed by steam sanitization (AED 89) for a hygienic finish. Because apartments here are often compact, we work efficiently around furniture without needing to move large pieces out of the unit. Quick-dry techniques mean most 3-seaters are ready to sit on again within 3–4 hours, and our vans reach Al Nahda quickly given its Dubai-border location, so same-day booking is rarely an issue.',
        landmarks: ['Sahara Centre', 'Al Nahda Park', 'Dubai–Sharjah border', 'Al Nahda Pond Park', 'Al Nahda Street', 'Sharjah Cooperative Society'],
        localNote: 'High-occupancy Al Nahda apartments collect dust quickly from nearby traffic and construction — a deep clean every 4–6 months keeps sofas fresh and hygienic. Because Al Nahda sits right at the Dubai border, our team can usually reach you within the same day.',
        faqs: [
          { q: 'Do you offer same-day sofa cleaning in Al Nahda Sharjah?', a: 'Yes — Al Nahda is right on the Dubai border, so our team reaches you quickly with same-day at-home sofa cleaning.' },
          { q: 'Do I need to take my sofa anywhere?', a: 'No. We clean your sofa at home in Al Nahda with all equipment brought to you.' },
          { q: 'How much does sofa cleaning cost in Al Nahda Sharjah?', a: 'Shampooing starts at AED 79, deep cleaning at AED 99, steam cleaning at AED 89, and leather care at AED 129, all with doorstep service.' },
          { q: 'Can you work around a small apartment layout in Al Nahda?', a: 'Yes — our team is used to compact Al Nahda units and cleans sofas in place without needing to move them outdoors.' },
          { q: 'How often should I clean my sofa if I live in Al Nahda?', a: 'Given the road and construction dust in the area, we recommend every 4–6 months, or every 3 months for ground and lower-floor units.' },
        ] },
      { slug: 'al-majaz', name: 'Al Majaz', short: 'Al Majaz', propertyType: 'waterfront apartments',
        intro: 'Al Majaz overlooks Khalid Lagoon with popular waterfront apartments that offer some of Sharjah’s best skyline and water views. The area draws families and professionals who enjoy evening walks along Al Majaz Waterfront and the Al Majaz Amphitheatre, but lagoon-side living brings its own upholstery challenges. Al Haya Sofa Care provides professional sofa deep cleaning and odor treatment for Al Majaz homes, handling lagoon-side humidity with fast-dry extraction so your furniture doesn’t stay damp for long.',
        whyClean: 'Sitting beside Khalid Lagoon means Al Majaz apartments deal with consistently higher ambient humidity than inland Sharjah districts, and that moisture seeps into sofa cushions and fabric backing over time. Left untreated, trapped humidity encourages musty odors and, in worst cases, mold spores inside foam padding that ordinary vacuuming can never reach. Waterfront balconies and open windows also let in fine airborne salt and dust, which settles into upholstery fibers. Routine professional steam cleaning and dehumidified drying keeps Al Majaz sofas smelling fresh and structurally sound.',
        serviceDetail: 'For Al Majaz homes we lean on fast-dry extraction cleaning, pulling out moisture immediately after shampooing so cushions don’t sit damp in a humid lagoon-side apartment. Steam cleaning (AED 89) handles odor at the source rather than masking it, and we finish with air-assisted drying to cut typical dry time down to around 3–4 hours even with the extra ambient humidity. For leather sectionals common in Al Majaz’s newer towers, our AED 129 leather conditioning treatment restores suppleness and guards against the humidity-driven cracking that coastal leather furniture is prone to.',
        landmarks: ['Al Majaz Waterfront', 'Khalid Lagoon', 'Al Noor Mosque', 'Al Majaz Amphitheatre', 'Sharjah Aquarium', 'Al Qasba Canal'],
        localNote: 'Lagoon-side humidity in Al Majaz can trap moisture in sofas, leading to musty odors if left untreated. Steam cleaning and deodorizing every 4 months keeps upholstery fresh, and we recommend leather conditioning twice a year for waterfront apartments.',
        faqs: [
          { q: 'Can you clean sofas in Al Majaz waterfront apartments?', a: 'Yes — we cover all Al Majaz buildings with at-home sofa shampoo, steam cleaning and stain removal.' },
          { q: 'Do you treat humidity odors from sofas?', a: 'Yes, our deodorizing steam treatment neutralizes musty, humidity-related odors at the source.' },
          { q: 'How long will my sofa stay damp after cleaning in Al Majaz?', a: 'With fast-dry extraction, most sofas are ready to use again in about 3–4 hours despite the lagoon-side humidity.' },
          { q: 'Do you offer leather care for Al Majaz apartments?', a: 'Yes — AED 129 leather cleaning and conditioning is available, ideal for protecting leather sofas from lagoon humidity.' },
          { q: 'Is booking available near Al Majaz Amphitheatre events?', a: 'Yes — we schedule around evening events at the Amphitheatre and Waterfront so cleaning won’t clash with your plans.' },
        ] },
      { slug: 'al-khan', name: 'Al Khan', short: 'Al Khan', propertyType: 'beachside residential towers',
        intro: 'Al Khan’s beachside towers enjoy sea views along the Gulf coast but also face constant salt-air humidity that tests any upholstery. The neighborhood sits close to Al Qasba and Maraya Art Centre, drawing residents who value both the coastal lifestyle and easy access to Sharjah’s cultural spots. Al Haya Sofa Care delivers at-home sofa deep shampoo and leather care across Al Khan, protecting upholstery from coastal moisture with fast-dry methods suited to sea-facing apartments.',
        whyClean: 'Salt-laden sea air is one of the toughest environments for sofa fabric and leather alike — fine salt particles settle into fibers and, combined with humidity, accelerate fading, stiffening and cracking far faster than in inland areas. Al Khan’s beachfront towers also see more sand tracked in from the shore, which acts like sandpaper on fabric weave with every use. Without regular deep cleaning, salt residue and trapped moisture can permanently discolor light-colored sofas and dry out leather until it splits at the seams.',
        serviceDetail: 'Our Al Khan service combines hot-water extraction shampooing to flush out embedded salt and sand with fast-dry techniques that prevent moisture from lingering in sea-facing units. For leather sofas — common in Al Khan’s upscale beachside towers — we apply pH-safe conditioning (AED 129) that restores oils lost to salt exposure and helps prevent cracking. Fabric sofas get the AED 99 deep-cleaning package, which lifts sand grit from deep within the weave rather than just surface-brushing it away, leaving cushions soft and residue-free.',
        landmarks: ['Al Khan Beach', 'Al Qasba', 'Maraya Art Centre', 'Eye of the Emirates', 'Sharjah Ladies Club', 'Flag Island'],
        localNote: 'Beachside Al Khan apartments benefit from fast-dry cleaning every 4–6 months to combat salt-air humidity, and leather sofas do best with conditioning every 6 months to prevent cracking. Sand tracked in from the beach also makes deep-fiber shampooing especially worthwhile here.',
        faqs: [
          { q: 'Do you serve Al Khan beachside towers?', a: 'Yes — at-home sofa cleaning across all Al Khan residential towers, same-day available.' },
          { q: 'Is leather sofa cleaning available in Al Khan?', a: 'Yes, with pH-safe leather conditioning to protect against coastal humidity.' },
          { q: 'Can you remove sand and salt residue from fabric sofas?', a: 'Yes — our deep-extraction shampooing lifts sand and salt grit from deep within the fabric weave, not just the surface.' },
          { q: 'How often should beachside Al Khan sofas be cleaned?', a: 'We recommend every 4–6 months for fabric and every 6 months for leather, given the salt-air exposure in Al Khan.' },
          { q: 'Do you cover towers near Al Qasba and Flag Island?', a: 'Yes — our team regularly services apartments around Al Qasba, Flag Island and the Al Khan waterfront.' },
        ] },
      { slug: 'al-taawun', name: 'Al Taawun', short: 'Al Taawun', propertyType: 'high-rise residential towers',
        intro: 'Al Taawun’s cluster of high-rise towers along the Dubai border houses many families drawn by its central location and lagoon views near Al Taawun Mall. The area has grown quickly, and many towers here are relatively new, with open-plan living rooms and large sectional sofas that see heavy daily use. Al Haya Sofa Care offers affordable, same-day at-home sofa shampoo and steam cleaning across Al Taawun, sized to handle both compact apartments and larger family units.',
        whyClean: 'Al Taawun’s position along a busy commuter corridor means constant road dust drifts into homes through balconies and AC intake, settling steadily into sofa fabric. Many households here are larger families with children, so sofas face frequent snacking, spills and everyday wear that build up faster than in smaller units. The area’s newer towers often feature light-colored fabric sofas that show dust and stains more visibly, making a consistent cleaning schedule especially important to keep furniture looking presentable.',
        serviceDetail: 'For Al Taawun families we typically recommend the AED 99 deep-cleaning package, which combines shampooing with stain-spot treatment for everyday spills from kids and daily living. Steam cleaning (AED 89) is popular for sanitizing shared family sofas between deep cleans. Our team can handle large L-shaped and sectional sofas common in Al Taawun’s newer towers without needing extra visits, and quick-dry extraction keeps cushions usable again within a few hours — important in busy households where the living room is in constant use.',
        landmarks: ['Al Taawun Mall', 'Corniche Al Taawun', 'Lagoon-side towers', 'Sharjah Golf and Shooting Club', 'Al Taawun Park'],
        localNote: 'Busy Al Taawun family apartments stay fresher with a professional deep clean every 4–6 months, or every 3 months in homes with young children. The area’s many light-colored sectional sofas especially benefit from routine stain treatment before marks set in permanently.',
        faqs: [
          { q: 'How much does sofa cleaning cost in Al Taawun?', a: 'From AED 79 for shampooing and AED 99 for deep cleaning, with at-home service included.' },
          { q: 'Do you offer weekend slots in Al Taawun?', a: 'Yes — weekend and evening slots are available to fit your schedule.' },
          { q: 'Can you clean large L-shaped sofas in Al Taawun towers?', a: 'Yes — we regularly service large sectional and L-shaped sofas common in Al Taawun’s newer high-rise units.' },
          { q: 'Do you remove stains from light-colored fabric sofas?', a: 'Yes — our deep-cleaning package includes targeted stain-spot treatment ideal for light fabrics that show marks easily.' },
          { q: 'Is same-day booking available near Al Taawun Mall?', a: 'Yes — given the area’s central location, same-day slots are usually available for towers around Al Taawun Mall.' },
        ] },
      { slug: 'muwaileh', name: 'Muwaileh', short: 'Muwaileh', propertyType: 'villas and family communities',
        intro: 'Muwaileh is a growing family community of villas and apartments near University City, popular with families who want more space than central Sharjah offers. Its proximity to Al Zahia and City Centre Al Zahia makes it a convenient suburb for young families, and many homes here have larger sofas and sectional seating to match spacious villa living rooms. Al Haya Sofa Care provides at-home sofa deep cleaning, stain and pet-hair removal across Muwaileh and Al Zahia, tailored to family-heavy households.',
        whyClean: 'Villa living in Muwaileh often means larger households with children and pets, both of which accelerate sofa wear through spills, pet hair and daily rough use that apartment sofas rarely see to the same degree. Sandy winds common on Sharjah’s outskirts also carry fine desert dust into villa compounds more than in the denser city center, settling into upholstery over time. Without regular deep cleaning and pet-hair extraction, allergens and trapped odors accumulate quickly in busy family living rooms, especially where sofas double as everyday play areas for kids.',
        serviceDetail: 'Our Muwaileh service focuses on family and pet-friendly cleaning — deep-extraction shampooing (AED 99) paired with enzyme-based pet stain and odor removal that breaks down residue rather than masking it. For villas with multiple large sofas or matching sectional sets, our team schedules enough time to clean the full living room in one visit. We also offer dedicated pet-hair extraction passes before shampooing, since embedded fur can clog standard cleaning if not removed first, and quick-dry finishing keeps busy family rooms back in use the same day.',
        landmarks: ['Al Zahia', 'University City', 'City Centre Al Zahia', 'Muwaileh Commercial', 'Sharjah American International School', 'Al Zahia Central Park'],
        localNote: 'Family villas in Muwaileh with kids and pets benefit from a deep clean every 3–4 months, and enzyme pet-stain treatment is worth adding at every visit. Desert dust drifting into villa compounds also means fabric sofas here collect grit faster than in central Sharjah.',
        faqs: [
          { q: 'Do you cover Muwaileh and Al Zahia?', a: 'Yes — at-home sofa cleaning across Muwaileh, Al Zahia and surrounding family communities.' },
          { q: 'Can you remove pet hair and stains?', a: 'Yes, deep pet-hair extraction and enzyme stain treatment are part of our service.' },
          { q: 'Do you clean multiple large sofas in one villa visit?', a: 'Yes — our team schedules enough time to handle full living-room seating sets in Muwaileh villas in a single visit.' },
          { q: 'Is enzyme treatment safe for kids and pets?', a: 'Yes — our enzyme-based stain and odor treatment is non-toxic and safe for households with children and pets.' },
          { q: 'How does desert dust affect sofas in Muwaileh villas?', a: 'Fine dust from surrounding open land settles into fabric faster than in denser city areas, so we recommend cleaning every 3–4 months.' },
        ] },
      { slug: 'al-qasimia', name: 'Al Qasimia', short: 'Al Qasimia', propertyType: 'central residential apartments',
        intro: 'Al Qasimia is a central Sharjah residential district with a mix of older and newer apartment buildings near Rolla Square and King Faisal Street. Its central location means heavy traffic and commercial activity nearby, and many long-term residents live in older buildings where upholstery has often gone years without professional attention. Al Haya Sofa Care offers reliable at-home sofa shampoo and steam cleaning across Al Qasimia, well suited to both older fabric sofas and newer furniture.',
        whyClean: 'As one of Sharjah’s older, more central districts, Al Qasimia sees heavier traffic congestion and commercial dust than newer suburbs, and that grime works into sofa fabric over years of daily use. Many apartments here are also older builds with less ventilation, which can trap odors and allergens in upholstery longer than in modern towers. For sofas that haven’t been professionally cleaned in a long time, ground-in dust and city grime often sit well below the surface, requiring proper hot-water extraction rather than a quick surface wipe to fully lift out.',
        serviceDetail: 'For Al Qasimia’s mix of older and newer apartments, we start with a fabric assessment to choose the right approach — deep hot-water extraction shampooing (AED 79–99) for sofas that haven’t been cleaned in years, or a lighter steam refresh (AED 89) for regularly maintained furniture. Central Al Qasimia’s dense street layout means our team plans routes carefully to keep to scheduled appointment times despite traffic. We finish every job with quick-dry techniques so sofas are back in use within a few hours, even in older units with less natural airflow.',
        landmarks: ['Rolla Square', 'Al Qasimia Park', 'King Faisal Street', 'Sharjah Central Market', 'Al Qasimia University', 'Al Arouba Street'],
        localNote: 'Central Al Qasimia apartments collect city dust and traffic grime quickly — regular professional cleaning every 4–6 months keeps sofas hygienic. Older buildings in the area especially benefit from a first deep clean if the sofa hasn’t been professionally treated before.',
        faqs: [
          { q: 'Do you serve Al Qasimia, Sharjah?', a: 'Yes — at-home sofa cleaning across all Al Qasimia buildings with same-day availability.' },
          { q: 'Are products safe for kids and pets?', a: 'Yes — all products are eco-friendly and non-toxic.' },
          { q: 'Can you deep clean a sofa that has never been professionally cleaned before?', a: 'Yes — we assess older, heavily used sofas and apply extra shampooing passes if needed to lift years of embedded dust.' },
          { q: 'Do you reach older buildings near Rolla Square easily?', a: 'Yes — our team is familiar with Al Qasimia’s central streets and plans routes around traffic to stay on schedule.' },
          { q: 'What’s the difference between shampooing and steam cleaning for my sofa?', a: 'Shampooing deep-cleans embedded dirt and stains, while steam cleaning sanitizes and freshens regularly maintained sofas — we recommend the right one after a quick fabric check.' },
        ] },
    ],
  },
  ajman: {
    key: 'ajman', cityName: 'Ajman', citySlug: 'sofa-cleaning-ajman',
    areas: [
      { slug: 'al-nuaimiya', name: 'Al Nuaimiya', short: 'Al Nuaimiya', propertyType: 'residential apartments',
        intro: 'Al Nuaimiya is one of Ajman’s busiest residential districts, packed with family apartment towers close to Ajman University and the Sharjah border. Many households here are large families sharing sofas daily, so fabric wears down and dust builds up faster than in quieter areas. Al Haya Sofa Care offers affordable at-home sofa shampoo, steam cleaning and stain removal across Al Nuaimiya, with technicians who know the tower layouts well. Same-day appointments are usually available, and we work around your building’s parking and lift access without hassle.',
        whyClean: 'Al Nuaimiya’s tightly packed towers trap indoor dust and traffic pollution from Sheikh Ammar bin Humaid Street, which settles into sofa fibers faster than in quieter neighborhoods. Large families and shared living arrangements common in the area mean sofas see heavier daily use, more spills and more foot traffic near seating. Combined with Ajman’s humid coastal climate, this creates ideal conditions for dust mites and bacteria to build up inside cushions that regular vacuuming cannot reach.',
        serviceDetail: 'Our Al Nuaimiya visits start with a fabric and stain assessment, followed by dry vacuuming to lift loose dust before any moisture is applied. We apply a pH-balanced shampoo suited to UAE humidity, agitate it into the fibers to break down grease and body oils, and extract it with low-moisture equipment that leaves the sofa nearly dry to the touch. Stubborn stains from food, tea or ink get targeted pre-treatment, and every visit finishes with a deodorizing pass so the sofa smells genuinely fresh.',
        landmarks: ['Al Nuaimiya Towers', 'Ajman University', 'Nesto Hypermarket', 'Sheikh Ammar bin Humaid Street', 'Al Nuaimiya Park'],
        localNote: 'Family apartments in Al Nuaimiya benefit from a deep clean every 4–6 months to control dust and allergens. With larger households and frequent guests common in the area, many residents prefer a clean every 3 months to keep sofas guest-ready.',
        faqs: [
          { q: 'Do you offer at-home sofa cleaning in Al Nuaimiya?', a: 'Yes — we bring all equipment to your home in Al Nuaimiya, with same-day slots available.' },
          { q: 'How much does it cost?', a: 'From AED 79 for shampooing and AED 99 for deep cleaning.' },
          { q: 'Can you clean large sofas for big families in Al Nuaimiya?', a: 'Yes — many Al Nuaimiya homes have 6 or 7-seater sofas, and we price per seat with no hidden charges.' },
          { q: 'How quickly can I book a technician in Al Nuaimiya?', a: 'We usually offer same-day or next-day slots. Message us on WhatsApp at +971547199189 with your building name.' },
          { q: 'Do you clean sofas in apartments near Ajman University?', a: 'Yes, we regularly service apartments and shared housing near Ajman University, with quick turnarounds for busy households.' },
        ] },
      { slug: 'al-rashidiya', name: 'Al Rashidiya', short: 'Al Rashidiya', propertyType: 'apartments and villas',
        intro: 'Al Rashidiya is a central Ajman district of apartments and villas that sits close to the Corniche and City Centre Ajman, making it a convenient, walkable neighborhood for families. The mix of older apartment blocks and newer villas means upholstery styles vary widely, from basic fabric sofas to premium leather sets. Al Haya Sofa Care provides professional at-home sofa deep cleaning and leather care across Al Rashidiya, tailoring our approach to each home’s furniture and schedule. Whether you live in a compact flat or a family villa, our team arrives with everything needed for a full clean on-site.',
        whyClean: 'Being close to the Ajman Corniche, Al Rashidiya homes pick up salt-laden sea air that gradually dries out leather and dulls fabric colors if left untreated. The district’s constant foot traffic near City Centre Ajman and its shopping strip also means more dust and pollutants tracked indoors on shoes and clothing. Villas with gardens add another layer, as pollen and outdoor dirt migrate onto sofas through open doors and windows during Ajman’s milder months.',
        serviceDetail: 'For Al Rashidiya homes we begin with a moisture and fabric check to decide between fabric shampooing or leather-safe conditioning. Fabric sofas get a full shampoo-and-extract cycle with quick-dry techniques, while leather sofas receive a gentle pH-neutral cleanse followed by a conditioning treatment that restores suppleness and shine. We pay extra attention to piping, seams and armrests where Corniche humidity tends to cause the most damage over time.',
        landmarks: ['Ajman Corniche', 'City Centre Ajman', 'Al Rashidiya Towers', 'Ajman Museum', 'Al Rashidiya 1–3'],
        localNote: 'Corniche-area humidity makes regular sofa cleaning worthwhile in Al Rashidiya. We recommend a deep clean every 4–6 months for fabric sofas, and leather conditioning roughly every 3 months to prevent cracking from sea-air exposure.',
        faqs: [
          { q: 'Do you cover Al Rashidiya, Ajman?', a: 'Yes — at-home sofa cleaning across all Al Rashidiya apartments and villas.' },
          { q: 'Is leather cleaning available?', a: 'Yes, with pH-safe conditioning to protect leather from humidity.' },
          { q: 'Do you clean sofas in villas near the Corniche?', a: 'Yes — many Al Rashidiya villas near the Corniche get seasonal leather conditioning to counter salt-air drying.' },
          { q: 'Can I book after visiting City Centre Ajman?', a: 'Absolutely — we offer flexible evening and weekend slots so you can schedule around errands at City Centre Ajman.' },
          { q: 'Do you handle both fabric and leather sofas in the same home?', a: 'Yes, our technicians carry products for both fabric and leather and treat each piece with the right method during a single visit.' },
        ] },
      { slug: 'al-jurf', name: 'Al Jurf', short: 'Al Jurf', propertyType: 'villas and family homes',
        intro: 'Al Jurf is a quieter Ajman community of villas and family homes located near Ajman University and the China Mall industrial area. Households here tend to be spread across larger properties, often with pets and children who put daily wear on living-room and majlis seating. Al Haya Sofa Care offers at-home sofa deep cleaning, stain and pet-hair removal across Al Jurf, bringing a full mobile setup so nothing needs to leave the house. Our team is familiar with the area’s villa compounds and gate access requirements.',
        whyClean: 'Al Jurf’s proximity to industrial zones like China Mall and Al Jurf Industrial means fine dust and construction particles can drift into nearby villas, settling on fabric upholstery over time. Villa living also typically means more shoes and outdoor dirt tracked in through multiple entry points compared to apartments. Add pets, which are common in this family-oriented community, and sofas accumulate hair, dander and odor that standard home vacuuming struggles to fully remove.',
        serviceDetail: 'In Al Jurf we start by pre-treating visible pet hair and stains with an enzyme-based solution that breaks down odor-causing bacteria at the source rather than masking it. The sofa then goes through a full hot-water extraction shampoo cycle, which lifts embedded dust and industrial particulate from deep within the padding. We finish with a deodorizing treatment and, on request, a light fabric protector spray to make future pet messes easier to wipe up.',
        landmarks: ['Ajman University', 'Al Jurf Industrial', 'China Mall Ajman', 'Al Jurf Gardens', 'Sheikh Mohammed Bin Zayed Road'],
        localNote: 'Family villas in Al Jurf stay fresher with a deep clean every 3–4 months, especially with pets. Villas near the industrial side of Al Jurf may benefit from slightly more frequent cleaning to manage airborne dust settling on fabric.',
        faqs: [
          { q: 'Do you serve Al Jurf villas?', a: 'Yes — at-home sofa cleaning for villas and family homes across Al Jurf.' },
          { q: 'Can you remove pet stains and hair?', a: 'Yes — deep pet-hair extraction and enzyme stain treatment included.' },
          { q: 'Do you handle dust from nearby industrial areas?', a: 'Yes — our deep extraction method is designed to lift fine industrial dust that settles into fabric near Al Jurf Industrial.' },
          { q: 'Is your team familiar with villa compound access in Al Jurf?', a: 'Yes, we regularly service Al Jurf villa compounds and coordinate gate or security access ahead of your appointment.' },
          { q: 'Can I request a fabric protector after cleaning?', a: 'Yes — we offer an optional protective coat that makes future pet stains and spills easier to clean.' },
        ] },
      { slug: 'ajman-corniche', name: 'Ajman Corniche', short: 'Corniche', propertyType: 'beachfront apartments',
        intro: 'Ajman Corniche’s beachfront apartments enjoy sea views and a relaxed coastal lifestyle, but that same sea air brings constant salt-laden humidity into every home. Residents here often invest in higher-end fabric and leather sofas to match the premium waterfront setting, which deserve careful, specialist care. Al Haya Sofa Care delivers fast-dry sofa deep cleaning and odor treatment to protect upholstery along the Ajman Corniche, using techniques suited to coastal moisture. Our team is used to Corniche tower access and can schedule around sea-view apartment building procedures.',
        whyClean: 'Constant exposure to salt-air humidity along the Corniche accelerates fabric breakdown and causes leather to dry, crack or develop a musty smell faster than inland areas. Sea breeze also carries fine salt particles indoors through balconies and windows left open to enjoy the view, and these settle into upholstery fibers over time. Without regular professional attention, this combination can permanently dull colors and shorten the lifespan of even well-maintained sofas.',
        serviceDetail: 'For Corniche apartments we prioritize fast-dry extraction methods that pull moisture out efficiently, since coastal humidity already slows natural air-drying. Fabric sofas get a full shampoo and steam cycle followed by rapid extraction, while leather pieces receive a gentle salt-residue cleanse and conditioning treatment to restore flexibility. We also offer an optional protective fabric coat that helps repel humidity and stains between visits, ideal for Corniche apartments facing the sea.',
        landmarks: ['Ajman Corniche', 'Ajman Beach', 'Kempinski Ajman', 'Corniche Towers', 'Ajman Marina'],
        localNote: 'Salt-air humidity along the Corniche calls for fast-dry cleaning every 4–6 months. Apartments directly facing the beach with regularly opened windows may need cleaning closer to every 3 months to stay ahead of humidity buildup.',
        faqs: [
          { q: 'Do you cover Ajman Corniche apartments?', a: 'Yes — at-home sofa cleaning across all Corniche beachfront towers.' },
          { q: 'How do you handle humidity odors?', a: 'Our steam and deodorizing treatment neutralizes musty, humidity-related odors.' },
          { q: 'Can salt air damage my leather sofa over time?', a: 'Yes, without care it can dry and crack leather — our conditioning treatment specifically addresses this for Corniche homes.' },
          { q: 'How fast will my sofa dry given the coastal humidity?', a: 'With our fast-dry extraction, most sofas are usable within 3–4 hours even in Corniche humidity.' },
          { q: 'Do you offer a protective coating for beachfront sofas?', a: 'Yes — an optional fabric protector is available to help repel humidity and stains between professional cleans.' },
        ] },
    ],
  },
  'abu-dhabi': {
    key: 'abu-dhabi', cityName: 'Abu Dhabi', citySlug: 'sofa-cleaning-abu-dhabi',
    areas: [
      { slug: 'khalifa-city', name: 'Khalifa City', short: 'Khalifa City', propertyType: 'villas and family compounds',
        intro: 'Khalifa City is a spacious Abu Dhabi suburb of villas and family compounds spread across Khalifa City A and B, popular with families who want larger homes near the airport road. Living rooms and majlis areas here often feature big L-shaped or multi-piece sofa sets that see daily use from children, guests and pets. Al Haya Sofa Care provides at-home sofa deep cleaning, stain and pet-hair removal across Khalifa City A and B, arriving with mobile equipment sized for large family sofas. We plan appointments around villa gate access and compound schedules for a smooth visit.',
        whyClean: 'Khalifa City’s villa-style living means more outdoor dust and sand blow indoors through garden doors and driveways, especially during windy desert conditions. Large families and frequent gatherings common in the area put heavier daily wear on majlis and living-room seating than typical apartment use. Pets are also common in villa households, adding dander, hair and occasional accidents that regular vacuuming cannot fully remove from deep within cushion padding.',
        serviceDetail: 'For Khalifa City villas, we begin with a full inspection of each sofa piece since large sectional sets often combine different fabrics or cushion densities. Pet hair and stains are pre-treated with enzyme cleaners, then the full set goes through hot-water extraction shampooing piece by piece to keep drying times manageable. Because these sofas are large, we allocate extra time per visit and finish with a deodorizing treatment across the whole set so it smells fresh room-wide.',
        landmarks: ['Khalifa City A & B', 'Etihad Plaza', 'Safeer Mall', 'Abu Dhabi Airport Road', 'Khalifa City Community Centre'],
        localNote: 'Large villa sofas in Khalifa City benefit from a deep clean every 4–6 months, more often with kids or pets. Homes near unpaved plots or under construction nearby may need extra attention every 3 months due to blown-in sand and dust.',
        faqs: [
          { q: 'Do you serve villas in Khalifa City?', a: 'Yes — at-home sofa cleaning for villas and compounds across Khalifa City A and B.' },
          { q: 'Can you clean large L-shaped sofas?', a: 'Yes — we handle all sizes including large L-shaped and 7-seater sofas.' },
          { q: 'Do you clean majlis seating as well as living-room sofas?', a: 'Yes — we service majlis floor seating, cushions and living-room sofas in the same Khalifa City visit.' },
          { q: 'How do you handle sand tracked in from villa gardens?', a: 'Our deep extraction method lifts embedded sand and dust from cushions that regular vacuuming leaves behind.' },
          { q: 'Can you coordinate with villa security or gate access?', a: 'Yes, just share your compound or gate details when booking and we will coordinate arrival accordingly.' },
        ] },
      { slug: 'al-reem-island', name: 'Al Reem Island', short: 'Al Reem', propertyType: 'high-rise waterfront apartments',
        intro: 'Al Reem Island’s high-rise waterfront towers, including Shams Abu Dhabi and the Gate Towers, house a mix of young professionals and families who value convenience and quality. Sea humidity constantly surrounds these buildings, gradually affecting fabric and leather sofas if left unchecked. Al Haya Sofa Care offers at-home sofa shampoo, steam cleaning and fast-dry extraction across Al Reem Island towers, working efficiently within tower access and lift booking systems. Our technicians are experienced with high-rise building procedures across the island.',
        whyClean: 'Waterfront exposure on Al Reem Island means sea humidity seeps into apartments even with air conditioning running, slowly dampening upholstery fibers and encouraging musty odors. High-rise living also concentrates residents in smaller floor plans, so sofas often double as daily seating, workspace and guest area, increasing wear per square meter. Without periodic deep cleaning, trapped moisture in cushions can foster mold and bacteria growth that ordinary airing out cannot resolve.',
        serviceDetail: 'Our Al Reem Island visits focus heavily on moisture control given the island’s waterfront setting. We use fast-dry, low-moisture extraction equipment that removes shampoo and trapped humidity from fibers far more efficiently than standard steam alone, cutting drying time significantly. Every sofa also gets a final deodorizing pass to counter any lingering humidity-related odor, leaving apartments smelling clean rather than damp.',
        landmarks: ['Shams Abu Dhabi', 'Gate Towers', 'Sun & Sky Towers', 'Reem Mall', 'City of Lights'],
        localNote: 'Waterfront Al Reem apartments benefit from fast-dry cleaning every 4–6 months due to sea humidity. Units on lower floors closer to the water’s edge may want cleaning slightly more often to stay ahead of moisture buildup.',
        faqs: [
          { q: 'Do you cover Al Reem Island towers?', a: 'Yes — at-home sofa cleaning across Shams, Gate Towers, Sun & Sky and all Al Reem towers.' },
          { q: 'How long until the sofa is dry?', a: 'With fast-dry extraction, your sofa is usually ready within 3–4 hours.' },
          { q: 'Can humidity cause mold inside my sofa cushions?', a: 'Yes, trapped moisture can encourage mold over time — our low-moisture extraction removes this risk during each visit.' },
          { q: 'Do you need special building access for Reem Mall-area towers?', a: 'We simply need your tower name and any visitor registration details in advance — our team handles the rest.' },
          { q: 'Is steam cleaning safe for sea-facing apartment sofas?', a: 'Yes, we adjust technique to control moisture carefully so it suits the added ambient humidity of waterfront units.' },
        ] },
      { slug: 'yas-island', name: 'Yas Island', short: 'Yas Island', propertyType: 'modern villas and apartments',
        intro: 'Yas Island’s modern villas and apartments sit close to major leisure attractions like Yas Mall, Ferrari World and Yas Marina, home to many young families and professionals. Communities such as West Yas and Ansam feature contemporary interiors where sofas are often a centerpiece of open-plan living areas. Al Haya Sofa Care provides professional at-home sofa deep cleaning and sanitization across Yas Island communities, matching the polished standard residents expect from this destination neighborhood. We schedule flexibly around family activities and weekend outings common on the island.',
        whyClean: 'Frequent visits to and from Yas Island’s attractions mean more guests, outdoor dust and sunscreen or food residue making its way onto living-room sofas after a day out. Families with young children, common in West Yas and Ansam, generate more spills and everyday marks that build up between cleanings. The island’s newer developments also see higher humidity from surrounding water features and marina areas, which can gradually affect fabric freshness if not addressed regularly.',
        serviceDetail: 'On Yas Island we combine a full shampoo-and-extract cycle with high-temperature steam sanitization, which is especially popular with families wanting to reduce allergens and bacteria after busy days at nearby attractions. Fabric sofas are treated fiber by fiber to lift ground-in dust and food residue, while any leather pieces receive a matching conditioning pass. We finish each visit with a deodorizing treatment so homes feel fresh and guest-ready.',
        landmarks: ['Yas Mall', 'Yas Marina', 'Ferrari World', 'West Yas', 'Ansam', 'Yas Waterworld'],
        localNote: 'Family homes on Yas Island stay hygienic with a deep clean and steam sanitization every 4–6 months. Households with young children or frequent guest visits after days at Yas attractions often prefer a clean every 3 months.',
        faqs: [
          { q: 'Do you serve Yas Island villas and apartments?', a: 'Yes — at-home sofa cleaning across West Yas, Ansam, Mayan and all Yas Island communities.' },
          { q: 'Is steam sanitization available?', a: 'Yes — high-temperature steam that kills 99.9% of bacteria, ideal for families.' },
          { q: 'Can you remove sunscreen or food stains from sofas?', a: 'Yes — our pre-treatment specifically targets oily residues like sunscreen and food that are common after a day out on Yas Island.' },
          { q: 'Do you offer weekend appointments for busy Yas Island families?', a: 'Yes, we offer weekend and evening slots to fit around family activities and attraction visits.' },
          { q: 'Is the cleaning safe for children and pets on the sofa afterward?', a: 'Yes, all products are eco-friendly, non-toxic and safe once the sofa is dry.' },
        ] },
      { slug: 'al-raha-beach', name: 'Al Raha Beach', short: 'Al Raha', propertyType: 'beachfront apartments',
        intro: 'Al Raha Beach offers waterfront apartments across communities like Al Bandar, Al Zeina and Al Muneera, giving residents a premium coastal lifestyle along the Abu Dhabi coast. That same beachfront setting means constant salt-air exposure that affects upholstery quality faster than inland neighborhoods. Al Haya Sofa Care delivers fast-dry sofa deep cleaning and leather care that protects upholstery from salt-air humidity at Al Raha, using moisture-controlled methods suited to coastal apartments. Our team regularly services all three main Al Raha Beach communities.',
        whyClean: 'Direct beachfront positioning means Al Raha Beach apartments absorb salt particles and humidity through balconies and windows, which settle into fabric and accelerate leather drying and cracking. The premium finishes common in Al Bandar, Al Zeina and Al Muneera developments deserve gentle, specialist treatment rather than generic cleaning methods that could damage delicate upholstery. Left unaddressed, coastal humidity trapped in cushions can also lead to musty odors that regular airing struggles to clear.',
        serviceDetail: 'We approach Al Raha Beach homes with fast-dry extraction as the priority, minimizing the time moisture sits in fabric given the area’s already humid coastal air. Leather sofas get a pH-safe cleanse followed by conditioning that restores suppleness lost to salt exposure, while fabric pieces receive full shampoo-and-extract treatment with rapid drying. An optional protective coat is available to help repel future humidity and stains between visits.',
        landmarks: ['Al Bandar', 'Al Zeina', 'Al Muneera', 'Al Raha Mall', 'Al Raha Beach Promenade'],
        localNote: 'Beachfront Al Raha apartments benefit from fast-dry cleaning every 4–6 months. Ground and lower-floor units closer to the waterline may want a clean closer to every 3 months given greater humidity exposure.',
        faqs: [
          { q: 'Do you cover Al Raha Beach (Al Zeina, Al Muneera)?', a: 'Yes — at-home sofa cleaning across all Al Raha Beach communities.' },
          { q: 'Can you protect sofas from coastal humidity?', a: 'Yes — fast-dry extraction plus an optional protective coat repels humidity and stains.' },
          { q: 'Is leather conditioning included for Al Raha Beach homes?', a: 'Yes, leather conditioning is offered as part of our leather care service to counter salt-air drying.' },
          { q: 'How often should Al Bandar or Al Zeina residents book a clean?', a: 'We recommend every 4–6 months, or every 3 months for units directly facing the waterline.' },
          { q: 'Do you bring all equipment to Al Raha Beach apartments?', a: 'Yes, our mobile team carries everything needed — no need to move furniture or visit a shop.' },
        ] },
      { slug: 'mussafah', name: 'Mussafah', short: 'Mussafah', propertyType: 'residential and labour-camp housing',
        intro: 'Mussafah is a large residential and commercial district in Abu Dhabi, home to a wide mix of family apartments, worker accommodation and residential communities near Shabiya and Mafraq. With so many households across the district, demand for practical, affordable sofa care is high, and budgets vary from single-family homes to shared housing. Al Haya Sofa Care offers affordable, reliable at-home sofa shampoo and deep cleaning across Mussafah’s residential communities, keeping pricing transparent and accessible for all household types. We serve both individual apartments and larger shared accommodation setups.',
        whyClean: 'Mussafah’s mix of residential and industrial zones means airborne dust and particulate from nearby commercial activity can drift into homes more than in purely residential neighborhoods. High-occupancy housing common in parts of Mussafah also means sofas see frequent, heavy use from multiple residents, accelerating dirt buildup and fabric wear. Without regular deep cleaning, this combination of dust and heavy use can shorten the practical lifespan of budget and mid-range sofas alike.',
        serviceDetail: 'In Mussafah we focus on efficient, thorough cleaning that delivers real value for money. Each sofa gets a dry vacuum pass to remove loose dust, followed by a full shampoo and extraction cycle using the same professional-grade equipment we use across Abu Dhabi. We keep pricing transparent from the start, and for shared or multi-unit housing we can often schedule several sofas in one visit to save time and cost.',
        landmarks: ['Mussafah Shabiya', 'ICAD', 'Mussafah Industrial', 'Mafraq', 'Mussafah Mall'],
        localNote: 'Busy Mussafah homes benefit from regular professional cleaning to control dust and allergens. Given the district’s mix of residential and industrial activity, a clean every 3–4 months is often more practical than the standard 6-month interval.',
        faqs: [
          { q: 'Do you offer affordable sofa cleaning in Mussafah?', a: 'Yes — transparent pricing from AED 79, with at-home doorstep service in Mussafah.' },
          { q: 'Is same-day service available?', a: 'Yes — same-day slots are usually available in Mussafah.' },
          { q: 'Can you clean multiple sofas in shared housing at once?', a: 'Yes, we regularly service shared and multi-unit housing in Mussafah and can bundle several sofas into one visit.' },
          { q: 'Does industrial dust affect how often I should clean my sofa?', a: 'It can — homes near Mussafah Industrial or ICAD often benefit from cleaning every 3–4 months rather than 6.' },
          { q: 'Do you serve areas near Mafraq and Mussafah Shabiya?', a: 'Yes, we cover all residential pockets across Mussafah including Shabiya and areas near Mafraq.' },
        ] },
      { slug: 'al-khalidiyah', name: 'Al Khalidiyah', short: 'Khalidiyah', propertyType: 'central city apartments',
        intro: 'Al Khalidiyah is a central Abu Dhabi district of apartments near the Corniche and Khalidiyah Mall, popular with residents who want a walkable, city-center lifestyle. Buildings here range from established mid-rise blocks to newer developments, with sofas ranging from everyday fabric sets to higher-end leather pieces. Al Haya Sofa Care provides professional at-home sofa deep cleaning, leather care and stain removal across Al Khalidiyah, adapting our approach to each apartment’s furniture and building access. Our team is experienced with central Abu Dhabi parking and lift logistics.',
        whyClean: 'Al Khalidiyah’s central location means constant city traffic and foot activity around Khalidiyah Mall and the Corniche, which brings fine urban dust and pollution indoors more than in quieter suburbs. Being close to the Corniche also adds a degree of sea-air humidity that can affect leather and fabric over time, similar to other coastal-adjacent districts. Apartments here are often occupied by busy professionals with limited time for deep home cleaning, making sofas an easily overlooked source of built-up dust and allergens.',
        serviceDetail: 'For Al Khalidiyah apartments we run a full inspection to identify fabric type and any visible staining before starting, since city-center homes often mix fabric and leather pieces in one living room. Fabric sofas get a complete shampoo-and-extract cycle to lift embedded urban dust, while leather sofas receive pH-safe cleaning and conditioning to guard against Corniche-adjacent humidity. We work efficiently to fit into busy professional schedules, often completing a full clean within one to two hours.',
        landmarks: ['Khalidiyah Mall', 'Abu Dhabi Corniche', 'Khalidiya Park', 'Al Khalidiyah Street', 'Marina Mall access road'],
        localNote: 'Central Khalidiyah apartments collect city dust — a deep clean every 4–6 months keeps sofas fresh. Apartments closer to the Corniche side of the district may also want occasional leather conditioning to offset sea-air humidity.',
        faqs: [
          { q: 'Do you serve Al Khalidiyah, Abu Dhabi?', a: 'Yes — at-home sofa cleaning across all Al Khalidiyah buildings with same-day availability.' },
          { q: 'Do you clean leather sofas?', a: 'Yes — specialist pH-safe leather cleaning and conditioning are available.' },
          { q: 'How long does a typical Al Khalidiyah apartment visit take?', a: 'Most standard sofas are cleaned within 1–2 hours, fitting easily around a busy city-center schedule.' },
          { q: 'Can you fit around office hours for professionals in Al Khalidiyah?', a: 'Yes, we offer morning, evening and weekend slots to work around typical office schedules.' },
          { q: 'Does city dust near Khalidiyah Mall affect my sofa faster?', a: 'Yes, central traffic and foot activity add extra urban dust — regular cleaning every 4–6 months keeps this under control.' },
        ] },
    ],
  },
};

export const getEmirate = (key: string): EmirateConfig | undefined => emirates[key];
export const getArea = (emirateKey: string, slug: string): Area | undefined =>
  emirates[emirateKey]?.areas.find((a) => a.slug === slug);

export function buildAreaMetadata(emirateKey: string, slug: string): Metadata {
  const em = emirates[emirateKey];
  const area = getArea(emirateKey, slug);
  if (!em || !area) return {};
  const url = `${BASE}/${em.citySlug}/${slug}`;
  return {
    title: `Sofa Cleaning ${area.short}, ${em.cityName}`, // layout template appends brand
    description: `Professional sofa cleaning in ${area.name}, ${em.cityName} — at-home deep shampoo, steam cleaning, stain & pet-hair removal for ${area.propertyType}. Same-day from AED 79. Call +971547199189.`.slice(0, 158),
    keywords: [
      `sofa cleaning ${area.name}`,
      `sofa cleaning ${area.short}`,
      `sofa shampooing ${area.short} ${em.cityName}`,
      `sofa deep cleaning ${area.short}`,
      `upholstery cleaning ${area.short} ${em.cityName}`,
      `couch cleaning ${area.short}`,
      `leather sofa cleaning ${area.short}`,
      `same day sofa cleaning ${area.short}`,
      `sofa stain removal ${area.short} ${em.cityName}`,
      `at home sofa cleaning ${area.name}`,
    ],
    alternates: { canonical: url },
    openGraph: {
      title: `Sofa Cleaning ${area.name} | Al Haya Sofa Care UAE`,
      description: `At-home sofa deep shampoo & steam cleaning in ${area.name}, ${em.cityName}. Same-day, eco-friendly, from AED 79.`,
      url,
      type: 'website',
      images: [{ url: '/sofa-cleaning-dubai-professional.webp', width: 1200, height: 630, alt: `Sofa cleaning in ${area.name}, ${em.cityName} by Al Haya Sofa Care` }],
    },
  };
}
